/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppProvider: typeof import('./../features/admin/components/common/app-provider.vue')['default']
    ButtonIcon: typeof import('./../features/admin/components/custom/button-icon.vue')['default']
    ExceptionBase: typeof import('./../features/admin/components/common/exception-base.vue')['default']
    FaButton: typeof import('@fa/ui')['FaButton']
    FaSvgIcon: typeof import('@fa/ui')['FaSvgIcon']
    IconLocalLogo: typeof import('~icons/local/logo')['default']
    LangSwitch: typeof import('./../features/admin/components/common/lang-switch.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NCheckbox: typeof import('naive-ui')['NCheckbox']
    NDatePicker: typeof import('naive-ui')['NDatePicker']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NDivider: typeof import('naive-ui')['NDivider']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NInput: typeof import('naive-ui')['NInput']
    NLoadingBarProvider: typeof import('naive-ui')['NLoadingBarProvider']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    NSpace: typeof import('naive-ui')['NSpace']
    NSwitch: typeof import('naive-ui')['NSwitch']
    NTooltip: typeof import('naive-ui')['NTooltip']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SystemLogo: typeof import('./../features/admin/components/custom/system-logo.vue')['default']
    ThemeSchemaSwitch: typeof import('./../features/admin/components/common/theme-schema-switch.vue')['default']
    WaveBg: typeof import('./../features/admin/components/custom/wave-bg.vue')['default']
  }
}
